"""
make_icon.py -- builds the exe's icon and Windows version resource at BUILD
time, from the same code that draws the in-game sprites. The repo stays
asset-free: nothing here is committed, it all lands in build/gen/.

    python tools/make_icon.py          # writes build/gen/chopped.ico + version_info.txt

The icon is art.make_icon(): our lime-green hero hatchback on a dark badge
with a gold rim, because a bare 12x22 car on a white desktop looks like a
lost Tic Tac.
"""

import io
import os
import struct
import sys

os.environ.setdefault("SDL_VIDEODRIVER", "dummy")
os.environ.setdefault("SDL_AUDIODRIVER", "dummy")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import pygame  # noqa: E402

from chopped import config as C  # noqa: E402
from chopped import art  # noqa: E402

# Windows picks whichever of these fits the spot (taskbar, Explorer, Alt-Tab...)
SIZES = (16, 24, 32, 48, 64, 128, 256)


def png_bytes(surf):
    buf = io.BytesIO()
    pygame.image.save(surf, buf, "icon.png")
    return buf.getvalue()


def write_ico(path, sizes=SIZES):
    """ICO with PNG-compressed entries (fine on every Windows since Vista,
    and PyInstaller copies them into the exe as-is)."""
    images = [(sz, png_bytes(art.make_icon(sz))) for sz in sizes]
    head = struct.pack("<HHH", 0, 1, len(images))
    offset = len(head) + 16 * len(images)
    entries, blobs = [], []
    for sz, data in images:
        dim = 0 if sz >= 256 else sz          # 0 means 256 in ICO-speak
        entries.append(struct.pack("<BBBBHHII", dim, dim, 0, 0, 1, 32, len(data), offset))
        blobs.append(data)
        offset += len(data)
    with open(path, "wb") as f:
        f.write(head + b"".join(entries) + b"".join(blobs))


VERSION_TEMPLATE = """# UTF-8
# Generated by tools/make_icon.py -- do not edit, do not commit.
VSVersionInfo(
  ffi=FixedFileInfo(filevers=({a}, {b}, {c}, 0), prodvers=({a}, {b}, {c}, 0),
                    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('040904B0', [
      StringStruct('CompanyName', 'Chopped crew'),
      StringStruct('FileDescription', 'Chopped - co-op car theft chop shop'),
      StringStruct('FileVersion', '{a}.{b}.{c}.0'),
      StringStruct('InternalName', 'Chopped'),
      StringStruct('LegalCopyright', 'Made by Bryce MacKenzie and friends'),
      StringStruct('OriginalFilename', 'Chopped.exe'),
      StringStruct('ProductName', 'Chopped'),
      StringStruct('ProductVersion', '{a}.{b}.{c} (protocol {proto})')])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def write_version(path):
    a, b, c = C.RELEASE
    with open(path, "w", encoding="utf-8") as f:
        f.write(VERSION_TEMPLATE.format(a=a, b=b, c=c, proto=C.VERSION))


def main():
    out = os.path.join(ROOT, "build", "gen")
    os.makedirs(out, exist_ok=True)
    pygame.display.init()
    pygame.display.set_mode((1, 1))
    ico = os.path.join(out, "chopped.ico")
    write_ico(ico)
    pygame.image.save(art.make_icon(256), os.path.join(out, "chopped_256.png"))   # handy for READMEs/Discord
    write_version(os.path.join(out, "version_info.txt"))
    pygame.quit()
    print("== icon + version info written to %s" % out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
