"""
lines.py -- everything the city says to you. Kept in one place so the
writers' room (Bryce) can find it.
"""

PED_COMPLAINTS = [
    "HEY! I'M WALKING HERE!", "MY LATTE!!", "I'M CALLING MY MOM", "THAT'S ASSAULT BY HATCHBACK",
    "I HAVE A PODCAST, YOU KNOW", "RUDE.", "MY SPINE IS NOW A SQUIGGLE", "WATCH IT, JOYRIDER!",
    "I'M WRITING A STRONGLY WORDED YELP REVIEW", "NOT THE KNEES!",
]
OWNER_YELLS = [
    "OWNER: THAT'S MY CAR!!", "OWNER: I JUST PAID IT OFF!", "OWNER: COME BACK HERE!",
    "OWNER: IT HAS MY GYM BAG IN IT!", "OWNER: I KNOW WHERE YOU LIVE! (I DON'T)",
    "OWNER: THAT'S A 2004! IT'S A CLASSIC!",
]
CLOWN_LINES = ["HONK!", "HONK HONK!", "*SAD TROMBONE*", "A CLOWN SQUEAKS ANGRILY"]
PUNCH_LINES = ["PEDESTRIAN: OW! MY EVERYTHING!", "PEDESTRIAN: WHAT WAS THAT FOR?!",
               "PEDESTRIAN: I'M TELLING EVERYONE ON THE BUS", "PEDESTRIAN: THAT'S IT, I'M MOVING TO SURREY"]
SHOT_LINES = ["PEDESTRIAN: I'VE BEEN SHOT! (IT'S A GRAZE) (IT'S FINE)", "PEDESTRIAN: MY GOOD JACKET!",
              "PEDESTRIAN: I'M CALLING 911 AND MY LAWYER", "PEDESTRIAN: WHY?! I'M A DENTIST!"]
SURRENDER_LINES = ["PEDESTRIAN: OKAY OKAY! TAKE IT!", "PEDESTRIAN: DON'T SHOOT! I HAVE A PODCAST!",
                   "PEDESTRIAN: HANDS UP! SEE? HANDS! UP!"]
WALLET_EXTRAS = ["(AND A BUS PASS)", "(AND A GYM CARD, NEVER USED)", "(AND A PHOTO OF SOMEONE'S CAT)",
                 "(AND THREE LOTTERY TICKETS, ALL LOSERS)", "(AND A COUPON FOR TIM'S)"]
BAIL_LINES = ["DRIVER: I'M NOT PAID ENOUGH FOR THIS!", "DRIVER: KEEP IT! IT'S LEASED!",
              "DRIVER: I'M CALLING MY INSURANCE (AND MY MOM)", "DRIVER: NOPE. NOPE NOPE NOPE."]

# ---- v0.7: slapstick ---------------------------------------------------------------
BONK_LINES = ["PEDESTRIAN: WAS THAT A CAR DOOR?!", "PEDESTRIAN: OW! WHO THROWS A WHEEL?!",
              "PEDESTRIAN: I'VE BEEN HIT BY A... BUMPER??", "*BONK*", "PEDESTRIAN: MY SUNDAY IS RUINED"]
BRAWL_LINES = ["PEDESTRIAN: OH, IT'S ON NOW.", "PEDESTRIAN: I DID KRAV MAGA ONCE. ONE CLASS.",
               "PEDESTRIAN: YOU PICKED THE WRONG ACCOUNTANT!", "PEDESTRIAN: HOLD MY LATTE.",
               "PEDESTRIAN: I'M GONNA GET YOU, JOYRIDER!", "PEDESTRIAN: THAT'S MY GYM ARM YOU'RE MESSING WITH"]
HUMBLED_LINES = ["%s GOT DROPPED BY A GUY IN SANDALS", "%s WAS HUMBLED BY A PEDESTRIAN",
                 "%s LOST A FIGHT TO SOMEONE HOLDING GROCERIES", "%s GOT CLOTHESLINED BY A DENTIST"]
REFUND_LINES = ["...AND TOOK THEIR $%d BACK. FAIR'S FAIR.", "...AND GRABBED BACK THEIR $%d. KARMA HAS A RECEIPT."]
LAUGH_LINES = ["PEDESTRIAN: HAHAHA WHAT IS THAT", "PEDESTRIAN: IS HE OKAY? HE'S DOING THE WORM",
               "PEDESTRIAN: I'M FILMING THIS", "PEDESTRIAN: MY KID DANCES BETTER. MY KID IS ONE."]
OFFENDED_LINES = ["PEDESTRIAN: DID YOU JUST DANCE AT ME?", "PEDESTRIAN: THAT'S MY GRANDMA'S DANCE. YOU'RE DONE.",
                  "PEDESTRIAN: OKAY, NOW I'M OFFENDED"]
HOMERUN_LINES = ["%s: HOME RUN! THAT PEDESTRIAN IS IN ANOTHER TIME ZONE", "%s HIT A PEDESTRIAN OUT OF THE PARK",
                 "%s: HAYMAKER! THEY'LL LAND SOMEWHERE AROUND SURREY"]
STRIKE_LINES = ["%s BOWLED A STRIKE! (%d PEOPLE)", "STRIKE! %s KNOCKED DOWN %d PEOPLE WITH A PERSON",
                "%s: HUMAN BOWLING, %d PINS"]
WRIGGLE_LINES = ["PEDESTRIAN: PUT ME DOWN! PUT ME DOWN!", "THE PEDESTRIAN WRIGGLED FREE AND IS FURIOUS",
                 "PEDESTRIAN: I'M TELLING YOUR MOTHER"]
# ---- v0.8: the law, and what it does to you (toasts are cut at 60 characters) ----
OFFICER_LINES = ["OFFICER: STOP! POLICE!", "OFFICER: HANDS WHERE I CAN SEE 'EM!", "OFFICER: DON'T MAKE ME RUN!",
                 "OFFICER: YOU HAVE THE RIGHT TO REMAIN SILLY"]
TASED_LINES = ["%s: DON'T TASE ME, BRO!", "%s GOT TASED. THE HAIR WILL NEVER RECOVER",
               "%s RODE THE LIGHTNING. FOR TWO SECONDS", "ZZZZT! %s IS DOING THE WORM. INVOLUNTARILY"]
WASTED_LINES = ["%s GOT WASTED. -$%d IN MEDICAL BILLS", "WASTED. %s'S AMBULANCE RIDE: $%d",
                "%s IS DOWN. THE HOSPITAL SENT A $%d BILL"]
PHONE_CALL_LINES = ["%s USED THEIR ONE PHONE CALL TO ORDER A PIZZA",
                    "%s USED THEIR ONE PHONE CALL ON THEIR MUM",
                    "%s'S ONE PHONE CALL: A RADIO CONTEST. THEY LOST",
                    "%s USED THEIR PHONE CALL TO COMPLAIN ABOUT THE FOOD"]
GUARD_LINES = ["GUARD: BACK IN YOUR CELL!", "GUARD: NOT ON MY SHIFT!", "GUARD: I'M TOO OLD FOR THIS",
               "GUARD: THAT'S IT, NO PUDDING"]
BOXERS = ["LOVE HEARTS", "RUBBER DUCKS", "TINY SHERIFF BADGES", "'MONDAY' (IT'S NOT MONDAY)", "LEOPARD PRINT",
          "LITTLE TACOS"]
STREAKER_LINES = ["A STREAKER IS LOOSE! THE COPS ARE... DISTRACTED", "STREAKER ALERT. AVERT YOUR EYES",
                  "SOMEONE'S RUNNING THROUGH TOWN IN NOTHING BUT A SMILE"]
# rap-sheet names for the mugshot, by Player.rap key
CHARGES = {"gta": "GRAND THEFT AUTO", "carjack": "CARJACKING", "assault": "ASSAULT", "rob": "ROBBERY",
           "gun": "DISCHARGING A FIREARM", "cop": "ASSAULTING AN OFFICER", "gnome": "GNOME THEFT",
           "dance": "UNLICENSED DANCING", "litter": "LITTERING (BANANAS)", "bribe": "BRIBERY (DONUTS)",
           "yeet": "THROWING A PERSON", "speed": "SPEEDING", "break": "JAILBREAK",
           "copcar": "STEALING A POLICE CAR"}

# (v0.9) selling a car whole. %s = the model, %d = the money
WHOLE_SALE_LINES = [
    "SOLD THE %s WHOLE TO A MAN CALLED DAVE. HE DIDN'T ASK. +$%d",
    "A GUY IN A TRACKSUIT DROVE THE %s AWAY. CASH IN A CRISP PACKET: +$%d",
    "THE %s IS SOMEBODY ELSE'S PROBLEM NOW. +$%d",
    "SHIPPED THE %s OVERSEAS IN A CONTAINER MARKED 'BANANAS'. +$%d",
    "YOUR COUSIN'S MATE BOUGHT THE %s. NO RECEIPT. +$%d",
]

# (v0.9) cops at the shut shop door
DOOR_BANG_LINES = [
    "POLICE! OPEN UP! (BANG BANG BANG)",
    "COP: WE KNOW YOU'RE IN THERE! ...ARE YOU IN THERE?",
    "COP: OPEN THIS DOOR! (HE'S LOOKING FOR THE BUTTON. THERE ISN'T ONE ON HIS SIDE.)",
    "COP: THIS IS YOUR LAST WARNING! (IT ISN'T.)",
    "COP: DOES ANYONE HAVE A CROWBAR? ANYONE?",
]

# (v0.9) the silly department, round three
CHICKEN_SLAP_LINES = [
    "SQUEAK! THEY'RE ON THE FLOOR. THE CHICKEN IS FINE.",
    "BONK. THAT'S GOING IN THE GROUP CHAT.",
    "ASSAULT WITH A RUBBER CHICKEN. NOT ACTUALLY A CRIME. (WE CHECKED.)",
    "THE CHICKEN SQUEAKED. THEY WENT DOWN. PHYSICS HAS NO EXPLANATION.",
]
CHICKEN_PUNCH_LINES = [
    "BAWK!!",
    "YOU PUNCHED A CHICKEN. THE CHICKEN WILL REMEMBER THIS.",
    "FEATHERS EVERYWHERE. WHAT IS WRONG WITH YOU.",
]
MIME_PUNCH_LINES = [
    "THE MIME MIMES BEING PUNCHED. HONESTLY? VERY CONVINCING.",
    "THE MIME FALLS OVER IN SLOW MOTION. SILENTLY. FOREVER.",
    "THE MIME WOULD LIKE TO REPORT THIS, BUT CAN'T SAY ANYTHING.",
]
MIME_LINES = [
    "A MIME IS TRAPPED IN AN INVISIBLE BOX. YOU PRETEND NOT TO SEE HIM.",
    "THE MIME IS PULLING AN INVISIBLE ROPE. IT'S ATTACHED TO YOUR CAR, APPARENTLY.",
    "A MIME WALKS AGAINST THE WIND. THERE IS NO WIND.",
    "THE MIME HANDS YOU AN INVISIBLE FLOWER. YOU TAKE IT. WHAT ELSE CAN YOU DO.",
]
MIME_ROB_LINE = "YOU ROBBED THE MIME: $0. IT WAS AN INVISIBLE WALLET."
MIME_BOX_LINE = "THE MIME SEES YOUR CARDBOARD BOX AND WEEPS. FINALLY, A REAL ONE."
WHOOPEE_LINES = [
    "PFFFFFFT. %s STEPPED ON A WHOOPEE CUSHION.",
    "PFFFRRRRT! %s. EVERYBODY HEARD THAT.",
    "%s FOUND THE WHOOPEE CUSHION. THE STREET WILL NEVER FORGET.",
]
BOX_LINES = [
    "YOU ARE NOW A CARDBOARD BOX. STAND STILL. BE THE BOX.",
    "INTO THE BOX. IT WORKED IN THAT GAME. IT'LL WORK HERE.",
    "YOU'RE A BOX. BOXES DON'T COMMIT CRIMES. (STAY STILL.)",
]
COPCAR_LINES = [
    "OFFICER: HEY! THAT'S MY-- %s JUST DROVE OFF IN HIS POLICE CAR.",
    "%s STOLE A COP CAR. THE OFFICER IS STANDING IN THE ROAD WITH HIS MOUTH OPEN.",
    "RADIO: UNIT 7, WHERE ARE YOU? UNIT 7: ...ON FOOT. %s HAS MY CAR.",
]
CHICKEN_ROAD_LINES = [
    "WHY DID THE CHICKEN CROSS THE ROAD? IT DIDN'T.",
    "A CHICKEN TRIED TO CROSS THE ROAD. THE ROAD WON. FEATHERS.",
    "BAWK-- *THUD*. THE CHICKEN HAS LEFT THE CHAT.",
]
CHICKEN_SPOT_LINES = [
    "A CHICKEN IS CROSSING THE ROAD. NOBODY KNOWS WHY.",
    "THERE'S A CHICKEN IN THE ROAD. DON'T. DON'T YOU DARE.",
]
MONEY_TRUCK_LINES = [
    "THE MONEY TRUCK'S BACK DOORS FLY OPEN. IT'S RAINING CASH BAGS!",
    "KA-CHUNK. THE ARMOURED VAN SPRINGS A LEAK. THE LEAK IS MONEY.",
    "CASH BAGS ALL OVER THE ROAD. THE DRIVER HASN'T NOTICED.",
]
BIG_AIR_LINES = [
    "BIG AIR! %.1f SECONDS. +$%d FROM THE CROWD",
    "SEND IT! %.1f SECONDS OF HANG TIME. +$%d",
    "%.1f SECONDS AIRBORNE. THE SUSPENSION FILED A COMPLAINT. +$%d",
]
