"""
lines.py -- everything the city says to you. Kept in one place so the
writers' room (Bryce) can find it.
"""

PED_COMPLAINTS = [
    "HEY! I'M WALKING HERE!", "MY LATTE!!", "I'M CALLING MY MOM", "THAT'S ASSAULT BY HATCHBACK",
    "I HAVE A PODCAST, YOU KNOW", "RUDE.", "MY SPINE IS NOW A SQUIGGLE", "WATCH IT, JOYRIDER!",
    "I'M WRITING A STRONGLY WORDED YELP REVIEW", "NOT THE KNEES!",
]
OWNER_YELLS = [
    "OWNER: THAT'S MY CAR!!", "OWNER: I JUST PAID IT OFF!", "OWNER: COME BACK HERE!",
    "OWNER: IT HAS MY GYM BAG IN IT!", "OWNER: I KNOW WHERE YOU LIVE! (I DON'T)",
    "OWNER: THAT'S A 2004! IT'S A CLASSIC!",
]
CLOWN_LINES = ["HONK!", "HONK HONK!", "*SAD TROMBONE*", "A CLOWN SQUEAKS ANGRILY"]
PUNCH_LINES = ["PEDESTRIAN: OW! MY EVERYTHING!", "PEDESTRIAN: WHAT WAS THAT FOR?!",
               "PEDESTRIAN: I'M TELLING EVERYONE ON THE BUS", "PEDESTRIAN: THAT'S IT, I'M MOVING TO SURREY"]
SHOT_LINES = ["PEDESTRIAN: I'VE BEEN SHOT! (IT'S A GRAZE) (IT'S FINE)", "PEDESTRIAN: MY GOOD JACKET!",
              "PEDESTRIAN: I'M CALLING 911 AND MY LAWYER", "PEDESTRIAN: WHY?! I'M A DENTIST!"]
SURRENDER_LINES = ["PEDESTRIAN: OKAY OKAY! TAKE IT!", "PEDESTRIAN: DON'T SHOOT! I HAVE A PODCAST!",
                   "PEDESTRIAN: HANDS UP! SEE? HANDS! UP!"]
WALLET_EXTRAS = ["(AND A BUS PASS)", "(AND A GYM CARD, NEVER USED)", "(AND A PHOTO OF SOMEONE'S CAT)",
                 "(AND THREE LOTTERY TICKETS, ALL LOSERS)", "(AND A COUPON FOR TIM'S)"]
BAIL_LINES = ["DRIVER: I'M NOT PAID ENOUGH FOR THIS!", "DRIVER: KEEP IT! IT'S LEASED!",
              "DRIVER: I'M CALLING MY INSURANCE (AND MY MOM)", "DRIVER: NOPE. NOPE NOPE NOPE."]

# ---- v0.7: slapstick ---------------------------------------------------------------
BONK_LINES = ["PEDESTRIAN: WAS THAT A CAR DOOR?!", "PEDESTRIAN: OW! WHO THROWS A WHEEL?!",
              "PEDESTRIAN: I'VE BEEN HIT BY A... BUMPER??", "*BONK*", "PEDESTRIAN: MY SUNDAY IS RUINED"]
BRAWL_LINES = ["PEDESTRIAN: OH, IT'S ON NOW.", "PEDESTRIAN: I DID KRAV MAGA ONCE. ONE CLASS.",
               "PEDESTRIAN: YOU PICKED THE WRONG ACCOUNTANT!", "PEDESTRIAN: HOLD MY LATTE.",
               "PEDESTRIAN: I'M GONNA GET YOU, JOYRIDER!", "PEDESTRIAN: THAT'S MY GYM ARM YOU'RE MESSING WITH"]
HUMBLED_LINES = ["%s GOT DROPPED BY A GUY IN SANDALS", "%s WAS HUMBLED BY A PEDESTRIAN",
                 "%s LOST A FIGHT TO SOMEONE HOLDING GROCERIES", "%s GOT CLOTHESLINED BY A DENTIST"]
REFUND_LINES = ["...AND TOOK THEIR $%d BACK. FAIR'S FAIR.", "...AND GRABBED BACK THEIR $%d. KARMA HAS A RECEIPT."]
LAUGH_LINES = ["PEDESTRIAN: HAHAHA WHAT IS THAT", "PEDESTRIAN: IS HE OKAY? HE'S DOING THE WORM",
               "PEDESTRIAN: I'M FILMING THIS", "PEDESTRIAN: MY KID DANCES BETTER. MY KID IS ONE."]
OFFENDED_LINES = ["PEDESTRIAN: DID YOU JUST DANCE AT ME?", "PEDESTRIAN: THAT'S MY GRANDMA'S DANCE. YOU'RE DONE.",
                  "PEDESTRIAN: OKAY, NOW I'M OFFENDED"]
HOMERUN_LINES = ["%s: HOME RUN! THAT PEDESTRIAN IS IN ANOTHER TIME ZONE", "%s HIT A PEDESTRIAN OUT OF THE PARK",
                 "%s: HAYMAKER! THEY'LL LAND SOMEWHERE AROUND SURREY"]
STRIKE_LINES = ["%s BOWLED A STRIKE! (%d PEOPLE)", "STRIKE! %s KNOCKED DOWN %d PEOPLE WITH A PERSON",
                "%s: HUMAN BOWLING, %d PINS"]
WRIGGLE_LINES = ["PEDESTRIAN: PUT ME DOWN! PUT ME DOWN!", "THE PEDESTRIAN WRIGGLED FREE AND IS FURIOUS",
                 "PEDESTRIAN: I'M TELLING YOUR MOTHER"]
